### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Eunjinshin** [Eunjinshin/Bare-Minimum-Requirement#1]
### 만들고자 하는 기능
Todo 생성 기능

### 구현을 위해 해야하는 일
1. [ ] Todo에 필요한 객체 설정
2. [ ] Todo 작성 기능
3. [ ] Todo 작성한 내용 불러오기 기능
4. [ ] 작성한 내용 완료/미완료 기능
5. [ ] 작성한 내용 삭제 기능

### 예상 작업 시간
약 1~2일
